apiVersion: charts.helm.k8s.io/v1alpha1
kind: Cockroachdb
metadata:
  name: example
spec:
  Name: cdb
  Image: cockroachdb/cockroach
  ImageTag: v19.1.3
  ImagePullPolicy: Always
  Replicas: 3
  MaxUnavailable: 1
  Component: cockroachdb
  InternalGrpcPort: 26257
  ExternalGrpcPort: 26257
  InternalGrpcName: grpc
  ExternalGrpcName: grpc
  InternalHttpPort: 8080
  ExternalHttpPort: 8080
  HttpName: http
  Resources:
    requests:
      cpu: 500m
      memory: 512Mi
  InitPodResources: {}
  Storage: 10Gi
  StorageClass: null
  CacheSize: 25%
  MaxSQLMemory: 25%
  ClusterDomain: cluster.local
  NetworkPolicy:
    Enabled: false
    AllowExternal: true
  Service:
    type: ClusterIP
    annotations: {}
  PodManagementPolicy: Parallel
  UpdateStrategy:
    type: RollingUpdate
  NodeSelector: {}
  Tolerations: {}
  Secure:
    Enabled: false
    RequestCertsImage: cockroachdb/cockroach-k8s-request-cert
    RequestCertsImageTag: '0.4'
    ServiceAccount:
      Create: true
